{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "851a6810-24ac-4d23-9949-48eb9f564ee0",
   "metadata": {},
   "outputs": [],
   "source": [
    "                              12 FEBRUARY ASSINGMENT"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8443bef9-3c5e-4ebc-bcdf-809ccca83fec",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1.\n",
    "Ans:-\n",
    "      An Exception is an error that happens during the execution of a program. Whenever there is an error,\n",
    "      Python generates an exception that could be handled. It basically prevents the program from getting crashed.\n",
    "      \n",
    "    A syntax error occurs when the structure of a program does not conform to the rules of the programming language. \n",
    "    Syntax errors are usually detected by the compiler or interpreter when the program is being compiled or executed,\n",
    "    and they prevent the program from running. Syntax errors are usually caused by mistakes in the source code, \n",
    "    such as typos, omissions, or incorrect use of syntax.\n",
    "\n",
    "    An exception is an abnormal event that occurs during the execution of a program. Exceptions are usually caused by\n",
    "    runtime errors, such as dividing by zero, trying to access an element in an array with an out-of-bounds index,\n",
    "    or trying to access a file that does not exist. Exceptions are not syntax errors, but they can still prevent the\n",
    "    program from running if they are not handled properly.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a544668-685e-47be-a7b0-a04703beb0e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. What happens when an exception is not handled? Explain with an example.\n",
    "Ans:-\n",
    "If the exception is not handled by an except clause, the exception is re-raised after the finally clause has been executed\n",
    "\n",
    "#Example\n",
    "def divide(num1, num2):\n",
    "    divide = num1/num2\n",
    "    return divide\n",
    "\n",
    " '''if any number divided by 0 then error will come  so i create a exception and hanle it'''\n",
    "    \n",
    " def divide(num1,num2):\n",
    "    if num2 == 0:\n",
    "        print(\"Error: division by zero\")\n",
    "        result = None\n",
    "    else:\n",
    "        result = num1 / num2\n",
    "    return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2664b807-9b4f-4d5f-bcb7-1070fbee4baf",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3.Which Python statements are used to catch and handle exceptions? Explain with an example\n",
    "Ans:- we can use try and except statements to catch and handle exceptions. \n",
    "\n",
    "#Example\n",
    "\n",
    "num1 = input(\"Enter a number: \")\n",
    "num2 = input(\"Enter another number: \")\n",
    "\n",
    "try:\n",
    "    result = int(num1) / int(num2)\n",
    "    print(\"The result is:\", result)\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Cannot divide by zero.\")\n",
    "except ValueError:\n",
    "    print(\"Error: Invalid input. Please enter a number.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fdd4f734-f65d-4977-8895-bc04abfae35b",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4.\n",
    "Ans:-\n",
    "\n",
    "'''Try and else'''\n",
    "the try statement is used to catch and handle exceptions that may occur in a block of code. \n",
    "The else statement is used to define a block of code that should be executed if no exception is raised in the try block. \n",
    "\n",
    "#example\n",
    "\n",
    "try:                                      # code block that may raise an exception\n",
    "    num1 = int(input(\"Enter a number: \"))\n",
    "    num2 = int(input(\"Enter another number: \"))\n",
    "    result = num1 / num2\n",
    "except ValueError:\n",
    "    print(\"Error: Invalid input. Please enter a number.\")\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Cannot divide by zero.\")\n",
    "else:                                              # code block to execute if no exception is raised in the try block\n",
    "    print(\"The result of division is:\", result)\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "'''Finally'''                              # code block to execute irrespective of whether an exception is raised or not\n",
    "\n",
    "try:\n",
    "    file = open(\"example.txt\", \"r\")\n",
    "    file_contents = file.read()\n",
    "    print(file_contents)\n",
    "except FileNotFoundError:\n",
    "    print(\"Error: File not found.\")\n",
    "finally:\n",
    "    file.close()\n",
    "    \n",
    "here finally block is useful for tasks that need to be executed, even if an exception is raised, \n",
    "such as closing a file, releasing resources, or cleaning up temporary files.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "'''raise'''\n",
    "    the raise keyword is used to raise an exception explicitly. We can use the raise keyword to raise an exception \n",
    "    in response to a specific error condition that we detect in our code. \n",
    "\n",
    "     raise ExceptionType(\"Error message\")\n",
    "        \n",
    "        #example\n",
    "        \n",
    "def divide(num1, num2):\n",
    "    if num2 == 0:\n",
    "        raise ZeroDivisionError(\"Cannot divide by zero.\")\n",
    "    else:\n",
    "        return num1 / num2\n",
    "\n",
    "try:\n",
    "    result = divide(10, 0)\n",
    "    print(result)\n",
    "except ZeroDivisionError as error:\n",
    "    print(error)\n",
    "    \n",
    "    i understand in this example - the divide function takes two arguments num1 and num2 and returns the result of dividing \n",
    "    num1 by num2. If num2 is equal to zero, we raise a ZeroDivisionError using the raise keyword."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16c4df6b-42a3-4964-b8d2-2076c2e724ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example.\n",
    "Ans:- \n",
    "Custom exceptions in Python are user-defined exceptions that can be raised in response to specific error conditions in our code.\n",
    "We can create custom exceptions by defining a new class that inherits from the built-in Exception class or any other built-in exception class.\n",
    "\n",
    "We need custom exceptions to provide more specific information about the errors that occur in our code. \n",
    "#Example-  \n",
    "\n",
    "we are building a banking application, we may want to raise a InsufficientFundsError exception when a user tries to\n",
    "withdraw more money than their account balance. This custom exception provides more specific information about the error condition,\n",
    "making it easier to handle and debug errors in our code\n",
    "\n",
    "\n",
    "\n",
    "class InsufficientFundsError(Exception):\n",
    "    pass\n",
    "\n",
    "class BankAccount:\n",
    "    def __init__(self, balance):\n",
    "        self.balance = balance\n",
    "\n",
    "    def withdraw(self, amount):\n",
    "        if amount > self.balance:\n",
    "            raise InsufficientFundsError(\"Insufficient funds.\")\n",
    "        else:\n",
    "            self.balance -= amount\n",
    "            return self.balance\n",
    "\n",
    "try:\n",
    "    account = BankAccount(1000)\n",
    "    balance = account.withdraw(1500)\n",
    "    print(\"New balance:\", balance)\n",
    "except InsufficientFundsError as error:\n",
    "    print(\"Error:\", error)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01aad6f9-17f3-418c-b698-13411af653e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6.Create a custom exception class. Use this class to handle an exception.\n",
    "Ans:-\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
